# Generated by Django 5.2 on 2026-01-20 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_enrollment"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Enrollment",
        ),
    ]
