# Generated by Django 5.2 on 2026-01-20 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0004_delete_enrollment"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lesson",
            options={"ordering": ["course", "order", "created_at"]},
        ),
        migrations.AddField(
            model_name="lesson",
            name="duration_minutes",
            field=models.PositiveIntegerField(
                default=0, help_text="Estimated duration in minutes"
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="order",
            field=models.PositiveIntegerField(
                default=0, help_text="Order of lesson in course"
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="status",
            field=models.CharField(
                choices=[("draft", "Draft"), ("published", "Published")],
                default="draft",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
